# Generated by Django 3.2.5 on 2022-05-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_category_average_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='average_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
