# Generated by Django 3.2.5 on 2022-05-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'MEN'), ('women', 'WOMEN'), ('kids', 'KIDS')], max_length=5, null=True),
        ),
    ]
