# Generated by Django 3.2.5 on 2022-05-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('t-shirt', 'T-SHIRT'), ('trousers', 'Trousers'), ('shoes', 'Shoes'), ('dress', 'Dress'), ('shirt', 'Shirt'), ('jacket', 'Jacket')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'MEN'), ('women', 'WOMEN'), ('kids', 'KIDS'), ('unisex', 'UNISEX')], max_length=6, null=True),
        ),
    ]
